### ISSUE TITLE
Add is_os_type('BSD')

### ISSUE THREAD

**Issue by dolmen** [Perl-Toolchain-Gang/Perl-OSType#7]
I sometimes have to check if the operating system is of the BSD family because the command line tools often have different options/behaviors than on Linux. For example `stty` on darwin/FreeBSD/... has `-f` while Linux has `-F`.

So I would like to be able to check if `is_os_type('BSD')`.

**Comment by dolmen** [comment]
This is related to #4 as [Perl::osnames](https://metacpan.org/pod/Perl::osnames#DESCRIPTION) has the `bsd` tag.

**Comment by Leont** [comment]
To me this is a slippery slope. How do you define what is a BSD and what isn't? E.g. for many purposes Linux is more BSDish than typical SysV unices.

In your use-case, actually detecting how the stty works (for example using stty --help) may be more reliable. YMMV.

**Comment by dolmen** [comment]
(for my use case I found a workaround: [to not use `F`/`f` at all](https://github.com/dolmen/angel-PS1/blob/devel/lib/AngelPS1/Plugin/Term/Size.pm#L39))
